apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-replicaset-t3q4
  labels:
    app: httpd_app_t3q4
    type: front-end-t3q4
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd_app_t3q4
  template:
    metadata:
      labels:
        app: httpd_app_t3q4
        type: front-end-t3q4
    spec:
      containers:
      - name: httpd-container-t3q4
        image: httpd:latest
