apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: xfusion
spec:
  containers:
  - name: time-check
    image: busybox:latest
    command: ["sh", "-c", "while true; do date > /opt/devops/time/time-check.log; sleep $TIME_FREQ; done"]
    env:
      - name: TIME_FREQ
        valueFrom:
          configMapKeyRef:
            name: time-config
            key: TIME_FREQ
    volumeMounts:
    - name: log-volume
      mountPath: /opt/devops/time
  volumes:
  - name: log-volume
    emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: xfusion
data:
  TIME_FREQ: "8"

