---
apps:
  hosts:    
    stapp01:
      ansible_user: tony
      ansible_password: Ir0nM@n
      ansible_become_password: Ir0nM@n
    stapp02:
      ansible_user: steve
      ansible_password: Am3ric@
      ansible_become_password: Am3ric@
    stapp03:
      ansible_user: banner
      ansible_password: BigGr33n
      ansible_become_password: BigGr33n
storage:
  hosts:
    ststor01:
      ansible_user: natasha
      ansible_password: Bl@kW
      ansible_become_password: Bl@kW    
backup:
  hosts:
    stbkp01:
      ansible_user: clint
      ansible_password: H@wk3y3
      ansible_become_password: H@wk3y3        
wsl:
  hosts:
    localhost:
      ansible_user: user
      connection: local