---
apps:
  hosts:
    stapp01:
      ansible_user: tony
      ansible_password: Ir0nM@n
      ansible_become_password: Ir0nM@n
    stapp02:
      ansible_user: steve
      ansible_password: Am3ric@
      ansible_become_password: Am3ric@
    stapp03:
      ansible_user: banner
      ansible_password: BigGr33n
      ansible_become_password: BigGr33n
    ststor01:
      ansible_user: natasha
      ansible_password: Bl@kW
      ansible_become_password: Bl@kW    

wsl:
  hosts:
    localhost:
      ansible_user: user
      connection: local