---
- name: KD task 7
  hosts: apps
  become: yes
  
  tasks:
    - name: Disable root login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
     notify:
       - restart ssh

  handlers:
    - name: restart ssh
      systemctl:
        name: sshd
        state: restarted