---
- name: Task 5 "Linux SSH Authentication"
  hosts: apps
  become: true
  tasks:  
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '/home/thor/.ssh/id_rsa.pub') }}"
    - name: Enable sudo 
      community.general.sudoers:
        name: root
        state: present
        user: "{{ ansible_user }}"
        runas: root
        commands: ALL