---
- name: Task 6 "Linux Find Command"
  hosts: stapp02
  become: true
  tasks: 
    - name: Install rsync
      package: 
        name: rsync
        state: latest
    - name: Copy php files
      command: rsync -av --include='*/' --include='*.php' --exclude='*' /var/www/html/media/ /media/
