apiVersion: v1 
kind: Service
metadata:
  name: gf-service
spec:
  type: NodePort
  selector:
    app: gf
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment-devops
  labels:
    app: gf
spec:
  selector:
   matchLabels:
    app: gf
  template:
    metadata:
      labels:
        app: gf 
    spec:
      containers:
        - name: gf-container
          image: grafana/grafana-oss
          ports:
            - containerPort: 3000
  