---
- name: Task 17 "Firewall Configuration"
  become: true
  hosts: backup
  tasks:    
    - name: Start and enable firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes
    - name: Allow incoming connections on port 6400
      ansible.posix.firewalld:
        port: 6400/tcp
        permanent: true
        zone: public
        state: enabled    
    - name: Reload firewalld to apply changes
      command: systemctl reload firewalld
