---
- name: Linux User Setup with Non-Interactive Shell
  hosts: stapp03

  vars:
    user: "mariyam"

  tasks:
  - name: Create a user named siva with a non-interactive shell on the App Server 3.
    ansible.builtin.user:
      name: "{{user}}"
      state: present
      shell: /usr/sbin/nologin
  